name: docker-build
on:
  pull_request:
  push:
    branches: [main]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
      - "maintenance"

permissions:
  contents: read

env:
  SERVICE_ACCOUNT: github@randamu-prod.iam.gserviceaccount.com
  DOCKER_REGISTRY: europe-west1-docker.pkg.dev/randamu-prod/candyland
  IMAGE_MAINTAINER: "Randamu"
  IMAGE_VENDOR: "Randamu"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout üõéÔ∏è
        uses: "actions/checkout@v4"
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: recursive

      - name: Login to Artifact Registry
        uses: "docker/login-action@v3"
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/faucet
          labels: |
            maintainer=${{ env.IMAGE_MAINTAINER }}
            org.opencontainers.image.title=faucet
            org.opencontainers.image.description="A faucet for test tokens"
            org.opencontainers.image.vendor=${{ env.IMAGE_VENDOR }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=sha,prefix=
            type=ref,event=branch,suffix=-latest,enable=${{ startsWith(github.ref, 'refs/heads/') }}
            type=semver,pattern={{version}},event=tag,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # this might not work at all, but might work and
          # allow us to bypass dockerhub ratelimit
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]
          ## this does work to avoid the dockerhub ratelimit
          driver-opts: |
            image=mirror.gcr.io/moby/buildkit:buildx-stable-1
            network=host

      - name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          github-token: "${{ secrets.PAT_TOKEN }}"
          build-args: |
            NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          cache-from: |
            type=registry,ref=${{ env.DOCKER_REGISTRY }}/faucet-cache:${{ steps.meta.outputs.version }}
            type=registry,ref=${{ env.DOCKER_REGISTRY }}/faucet-cache:main-latest
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/faucet-cache:${{ steps.meta.outputs.version }},mode=max
